CREATE TABLE CUSTOMER_ORDERS (
    ORDER_ID CHAR(12) NOT NULL,
    CUSTOMER_ID CHAR(10) NOT NULL,
    ORDER_TOTAL DECIMAL(9,2) NOT NULL,
    ORDER_STATUS CHAR(1) DEFAULT 'N',
    CREATED_TS TIMESTAMP NOT NULL
        DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_CUSTOMER_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_CUSTOMER_ORDERS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER_MASTER (CUSTOMER_ID)
);
